### ISSUE TITLE
crash： The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by Ztiany** [xfumihiro/ViewInspector#11]
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime: FATAL EXCEPTION: main
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime: Process: com.ztiany.imageselector, PID: 31217
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3786)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3758)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.insertScalpelLayout(ViewInspectorInterceptor.java:272)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.onMeasure(ViewInspectorInterceptor.java:166)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.ztiany.imageselector.view_inspector.ProbeProxy$android_widget_FrameLayout.onMeasure(ProbeProxy$android_widget_FrameLayout.java:20)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.ztiany.imageselector.view_inspector.ProbeProxy$android_widget_LinearLayout.invokeOnMeasure(ProbeProxy$android_widget_LinearLayout.java:27)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at view_inspector.probe.Interceptor.invokeOnMeasure(Interceptor.java:59)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at view_inspector.probe.Interceptor.onMeasure(Interceptor.java:51)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at view_inspector.probe.ViewInspectorInterceptor.onMeasure(ViewInspectorInterceptor.java:176)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.ztiany.imageselector.view_inspector.ProbeProxy$android_widget_LinearLayout.onMeasure(ProbeProxy$android_widget_LinearLayout.java:20)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-26 12:50:45.463 31217-31217/com.ztiany.imageselector E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by xfumihiro** [comment]
Is it possible to share the code of your application? If not, please give some more insight of it, for instance, the API level, steps to reproduce the crash, the third-party libraries you're using.
