### ISSUE TITLE
VectorDrawable causes the crash on pre-Lollipop

### ISSUE THREAD

**Issue by kissazi2** [xfumihiro/ViewInspector#20]
It can only run in android 5.0?

`````` java
591-591/com.github.xfumihiro.view_inspector.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.github.xfumihiro.view_inspector.sample, PID: 591
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.xfumihiro.view_inspector.sample/viewinspector.sample.MainActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class android.widget.ImageButton
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2192)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.widget.ImageButton
            at android.view.LayoutInflater.createView(LayoutInflater.java:623)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:465)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.view.View.inflate(View.java:17500)
            at view_inspector.ui.ViewInspectorToolbar.<init>(ViewInspectorToolbar.java:60)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:23)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:9)
            at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:53)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:11)
            at view_inspector.dagger.DaggerActivityComponent.inject(DaggerActivityComponent.java:261)
            at view_inspector.weaving.ViewInspectorAspect.injectViewInspector(ViewInspectorAspect.java:70)
            at viewinspector.sample.MainActivity.onCreate(MainActivity.java:11)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2156)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:597)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:465)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.view.View.inflate(View.java:17500)
            at view_inspector.ui.ViewInspectorToolbar.<init>(ViewInspectorToolbar.java:60)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:23)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:9)
            at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:53)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:11)
            at view_inspector.dagger.DaggerActivityComponent.inject(DaggerActivityComponent.java:261)
            at view_inspector.weaving.ViewInspectorAspect.injectViewInspector(ViewInspectorAspect.java:70)
            at viewinspector.sample.MainActivity.onCreate(MainActivity.java:11)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2156)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_chevron_left_white_24px.xml from drawable resource ID #0x7f020033
            at android.content.res.Resources.loadDrawable(Resources.java:2149)
            at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:348)
            at android.content.res.Resources.loadDrawable(Resources.java:2072)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.widget.ImageView.<init>(ImageView.java:129)
            at android.widget.ImageButton.<init>(ImageButton.java:87)
            at android.widget.ImageButton.<init>(ImageButton.java:83)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:597)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:465)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.view.View.inflate(View.java:17500)
            at view_inspector.ui.ViewInspectorToolbar.<init>(ViewInspectorToolbar.java:60)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:23)
            at view_inspector.ui.ViewInspectorToolbar_Factory.get(ViewInspectorToolbar_Factory.java:9)
            at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:53)
            at view_inspector.weaving.ViewInspectorAspect_MembersInjector.injectMembers(ViewInspectorAspect_MembersInjector.java:11)
            at view_inspector.dagger.DaggerActivityComponent.inject(DaggerActivityComponent.java:261)
            at view_inspector.weaving.ViewInspectorAspect.injectViewInspector(ViewInspectorAspect.java:70)
            at viewinspector.sample.MainActivity.onCreate(MainActivity.java:11)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2156)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5049)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:935)
            at android.graphics.drawable.

``` java
``````

**Comment by xfumihiro** [comment]
Can you share the build.gradle file?

**Comment by xfumihiro** [comment]
What API level are you on?

**Comment by xfumihiro** [comment]
Currently won't support 6.0 because of the permission issue.

**Comment by kissazi2** [comment]
genymotion  android 4.4.4 API 19
xiaomi note Andrioid 4.4.4 API 19
in devices list above，can't run sample .in Android 5.0 work well.

**Comment by xfumihiro** [comment]
Should only work with API >= 21 (but not Marshmallow) for now.

**Comment by hoombar** [comment]
I would be keen to see this running on API 16+. That is currently what all of my apps support.
If you're willing to move down this route, I will happily fork and submit a pull request for it.

**Comment by xfumihiro** [comment]
I'm thinking of making runtime modules(v14, v21, v23) to support API levels which then automatically  get picked by the plugin itself. This way the UI (mostly dialogs) can be pretty on each API level. Nevertheless, it is needed for Marshmallow due to the permission management issue. Any thoughts?

**Comment by vkotovv** [comment]
I think it should be mentioned in Readme that it supports only API >= 21 for now. It was a surprize for me.

**Comment by xfumihiro** [comment]
@hoombar API 16+ for minSdkVersion or compileSdkVersion?

**Comment by xfumihiro** [comment]
@vkotovv It's compileSdkVersion that must be greater than 21.

**Comment by Young55555** [comment]
Writer Line
