### ISSUE TITLE
i have a  ClassCastException, do you know how to solve it ?

### ISSUE THREAD

**Issue by sk284525908** [xfumihiro/ViewInspector#38]
10-30 14:16:39.231  32462-32462/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.sun.mylab, PID: 32462
    java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
            at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:448)
            at android.view.View.measure(View.java:17676)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5539)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2676)
            at android.view.View.measure(View.java:17676)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2046)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1192)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1402)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1080)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5952)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5384)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by xfumihiro** [comment]
Yup, aware of that ActionBarOverlay casting issue.
I'm busy with Marshmallow issue right now. (will close the issue in few hours!)
PRs are welcome!
