### ISSUE TITLE
Overlay Error

### ISSUE THREAD

**Issue by kikani89** [xfumihiro/ViewInspector#61]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: me.zhanghai.android.patternlock.sample, PID: 5194
                                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{me.zhanghai.android.patternlock.sample/me.zhanghai.android.patternlock.sample.app.LockScreenConfirm}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3124ada -- permission denied for this window type
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                       Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3124ada -- permission denied for this window type
                                                                                          at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                                          at android.app.Dialog.show(Dialog.java:319)
                                                                                          at me.zhanghai.android.patternlock.sample.util.utils.LockscreenUtils.lock(LockscreenUtils.java:52)
                                                                                          at me.zhanghai.android.patternlock.sample.app.LockScreenConfirm.lockHomeButton(LockScreenConfirm.java:228)
                                                                                          at me.zhanghai.android.patternlock.sample.app.LockScreenConfirm.onCreate(LockScreenConfirm.java:159)
                                                                                          at android.app.Activity.performCreate(Activity.java:6237)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
06-30 17:44:09.788 1661-4267/system_process E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9fe70740
06-30 17:44:12.822 1173-1290/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property

**Comment by kikani89** [comment]
give me some suggestion

**Comment by kikani89** [comment]
this will not work in lolipop and marshmallows
